version: '2'

services:
    tiane:
        container_name: tiane
        restart: always
        build: ./
        network_mode: "host"
        volumes:
            - .:/home/tiane
            - /etc/localtime:/etc/localtime:ro
