/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tiane_java_TIANEWrapper */

#ifndef _Included_tiane_java_TIANEWrapper
#define _Included_tiane_java_TIANEWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tiane_java_TIANEWrapper
 * Method:    startTiane
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tiane_java_TIANEWrapper_startTiane
  (JNIEnv *, jclass, jstring, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
